### ISSUE TITLE
reading large file using bigreadr

### ISSUE THREAD

**Issue by bioinfonext** [privefl/bigreadr#10]
Hi,

I do have large file and I was trying to read it by using bigreadr but I am keep getting error; Please help to resolve this.

```


> data2 <- big_fread2("df.num.txt", nb_parts = NULL, .transform = identity,.combine = cbind_df, skip = 0, select = NULL, progress = FALSE, part_size = 500 * 1024^2)
 *** caught segfault ***
address 0x7f5e51c63df7, cause 'memory not mapped'

Traceback:
 1: data.table::fread(input, ..., data.table = data.table, nThread = nThread)
 2: fread2(file, skip = skip, select = cols, ..., showProgress = FALSE)
 3: .transform(fread2(file, skip = skip, select = cols, ..., showProgress = FALSE))
 4: FUN(X[[i]], ...)
 5: lapply(split_cols, function(cols) {    part <- .transform(fread2(file, skip = skip, select = cols,         ..., showProgress = FALSE))    already_read <<- already_read + length(cols)    if (progress)         utils::setTxtProgressBar(pb, already_read)    part})
 6: big_fread2("df.num.txt", nb_parts = NULL, .transform = identity,     .combine = cbind_df, skip = 0, select = NULL, progress = FALSE,     part_size = 500 * 1024^2)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:
```

**Comment by privefl** [comment]
Why using bigreadr and not directly big_read()?

**Comment by bioinfonext** [comment]
Hi,

I have used this command but it never ends; and terminal got stuck on this command.

`data <- big_read(df.num.txt,select=1:844880)
`
Do I need to include any other options in this?

Many thanks,
Yogesh

**Comment by privefl** [comment]
You can try with `progress = TRUE`.
How long have you waited for?

**Comment by bioinfonext** [comment]
Hi@privefl,
Thanks for your help. it is taking long time and says will read file in 30 parts but it is at 0% from 30mins.
Does it need more RAM, and is there a way to read it quickly on HPC by increasing the number of cpu?

> data <- big_read("df.num.txt",select=1:844880, progress=TRUE)
Will read the file in 30 parts.
  |                                                                      |   0%


Many thanks,
Yogesh

**Comment by privefl** [comment]
Is it really that long?
How many lines (rows) do you have in your file?

**Comment by bioinfonext** [comment]
Hi Privefl,

I have 1984 rows and 844K columns

Many thanks,

**Comment by privefl** [comment]
How long does it take to do `bigreadr::fread2("df.num.txt", select = 1:8445)`?

**Comment by privefl** [comment]
It takes about 1 min for 1/10 of your data on my laptop:

```r
M <- 84488
N <- 1984
mat <- matrix(rnorm(M), N, M)
bigreadr::fwrite2(mat, "test.txt", sep = ",")
file.size("test.txt") / 1024^3  # 2.8 GB

system.time(
  X <- bigstatsr::big_read("test.txt", select = 1:M, 
                           backingfile = "test", progress = TRUE)
) # 54 sec
```

**Comment by bioinfonext** [comment]
Hi @privefl,

I do have 844880 columns and 1924 rows. For reading 8440 columns it is taking almost 30mins.


```

> X <- bigstatsr::big_read("df.num.txt", select = 1:8440, backingfile = "df.num", progress = TRUE)                                      
Will read the file in 30 parts.

  |======================================================================| 100%

```


Many thanks,

**Comment by privefl** [comment]
That's weird, it should take like 5-10 sec.

What do you have for `getOption("bigreadr.nThread")`?

**Comment by bioinfonext** [comment]
I am running R on slurm HPC by running the below command; so not sure about the number of cpu (thread).

```
srun --pty --partition=k2-hipri --mem-per-cpu=30G bash
module load apps/R/3.6.1/gcc-4.8.5+lapack-3.5.0+blas-3.6.0
module load libpng/16
R
```

**Comment by bioinfonext** [comment]
I am getting below answer for this command;
```
> getOption("bigreadr.nThread")
[1] 1
```

**Comment by privefl** [comment]
Maybe it's a problem of keeping the file in cache.
Try with more memory.

**Comment by bioinfonext** [comment]
Hi @privefl,

Thanks for your all help. I am working on Slurm HPC. So I was wondering if I can use here R-MPI library (https://cran.r-project.org/web/packages/Rmpi/Rmpi.pdf) to increase the bioreadr speed?

But I am not sure if can be possible?

Many thanks,

**Comment by privefl** [comment]
No, you can already use many cores to read in, but that's not the problem here I think (I have only 4 cores on my laptop anyway).

Do you use some weird partition where the access to disk is slow? 
If so, could you use a "faststorage" partition instead and put your file there instead?

**Comment by privefl** [comment]
Any update on this?
