### ISSUE TITLE
packaging for conda-forge

### ISSUE THREAD

**Issue by brendanf** [privefl/bigreadr#7]
Hi @privefl, I'm working on packaging bigreadr and bigassertr for [conda-forge](https://conda-forge.org/). You don't have to do anything, but I can list you as a [maintainer](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch) for the conda package if you want.

In practice, there isn't a lot to do, because there is a bot which automatically updates the conda recipe and submits a pull request whenever a new version is published on CRAN. As a maintainer, you would get notifications from the build process and be able to accept the pull requests, or fix things that need to be fixed, and would also get notifications if anyone files issues via the conda package.

Let me know if you want to be listed!

**Comment by privefl** [comment]
Hi,
I'm not very familiar with conda-forge, but I think they're using it at my new work place (for installing packages on some computing cluster, right?).
So, maybe it would make sense for me to learn how to add my packages there.
Is it also possible to add packages that are not on CRAN?

**Comment by brendanf** [comment]
Yes, Conda is a package and environment manager ([miniconda](https://docs.conda.io/en/latest/miniconda.html) -- only installs the core functionality, or [anaconda](https://www.anaconda.com/distribution/) -- also installs a lot of packages). You are right, people use it a lot on computing clusters, or at least for scientific computing.

Conda calls a repository for packages a "channel".  Anaconda itself has several default channels, [Conda-forge](https://conda-forge.org/) is one big publicly maintained channel, and it's also possible to have a personal public channel at anaconda.org.  Some companies also host private channels for their own networks .

It is pretty easy to make conda packages from github repositories.  Once you have conda installed then:

```sh
conda install build #only the first time
conda skeleton cran bigreadr #make a minimal recipe using CRAN
conda skeleton cran https://github.com/privefl/bigreadr #make the recipe from most recent release tag on github
conda build r-bigreadr #build the package from the recipe.
```
Assuming all the dependencies are already available as conda packages, that's it.  It can even be configured to upload it directly to a personal channel upon a successful build.

However, Conda-forge in particular [aims to make packages only from stable sources](https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos); for R packages this means CRAN unless there is some compelling reason why the package can't be released on CRAN.

`bigassertr` is [ready to go](https://github.com/conda-forge/staged-recipes/pull/10180); do you want me to add you to the maintainer list?

**Comment by privefl** [comment]
Ok
