### ISSUE TITLE
read gz files

### ISSUE THREAD

**Issue by variani** [privefl/bigreadr#8]
Hi Florian,

Nice idea about splitting. It was fun to see how it works.

Do you think it is possible to extend the same splitting idea for gz files? Imagine I have 4Gb gz file, and I don't want to decompress it before reading into R. The function `data.table::fread` supports gz input files and requires 'R.utils'. 

```
library(bigreadr)
library(readr)

f <- "tmp.csv.gz"
write_csv(iris[rep(seq_len(nrow(iris)), 1e2), ], f)

# read by readr
read1 <- read_csv(f)

# read by fread (R.utils)
stopifnot(require(R.utils))
read2 <- data.table::fread(f)

# read by bigreadr
read3 <- big_fread1(f, every_nlines = 100)
```

I got an error running the last line of code.

**Comment by privefl** [comment]
I don't this I support splitting compressed files, unfortunately. 

You have 2 solutions:
 - either decompress the whole file and use `big_fread1()`
 - or use `big_fread2()` that does not split the file but reads only a subset of columns at once

**Comment by variani** [comment]
The function `big_fread2` works fine on a small data file `tmp.csv.gz` (15K rows, 4 columns, 3Kb in gz), but I got an error on my target file (200K rows, 20K columns, 4.7Gb in gz):

```
> big_fread2(f, select = 1:2, progress = TRUE)
Will read the file in 10 parts.
  |                                                                      |   0%System errno 22 unmapping file: Invalid argument
Error in data.table::fread(input, ..., data.table = data.table, nThread = nThread) : 
  Opened 14.26GB (15311208448 bytes) file ok but could not memory map it. This is a 64bit process. There is probably not enough contiguous virtual memory available.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

Obviously, my machine has only 8Gb of RAM, and it is not enough for `big_fread2`. It seems your function decompresses the entire file (`14.26GB` in the error message). 

As an alternative solution, I used the following combo and pass it as `cmd` argument to `data.table::fread`:

```
cmd <- "gzip -dc <file> | cut -d ' ' -f1,2"
data.table::fread(cmd = cmd)
```

It takes ~7min on the same machine. I am curious if you have an explanation for this?

**Comment by privefl** [comment]
Yes, apparently `data.table::fread()` tries to map the whole file even if you request to read only the first two columns (I guess they can't do otherwise).

I'm not very familiar with the `cut` Unix command, but I guess that you ask to print the two first words for each line after decompressing the file, and read only these two first columns with `fread()`.

**Comment by variani** [comment]
Yes, `cut` subsets data to 2 columns and saves memory. I think the improvement comes from decompressing on the fly, which is more costly for CPU but more efficient for memory usage. 

Thank you for the feedback.

**Comment by privefl** [comment]
I would certainly want to be able to decompress on the fly.

If anyone has any idea on how to do this in C++, it would be great.
