### ISSUE TITLE
split_file poduces files with ".txt" extension only. 

### ISSUE THREAD

**Issue by nassuphis** [privefl/bigreadr#9]
it would be useful to be able to do files named ".csv"
so that split files can be opened using the arrow package as a single dataset.
can rename files manually, of course, but it would be cleaner to allow for ".csv" extension

**Comment by privefl** [comment]
Feel free to propose a pull request.

BTW, i would be surprised if the extension actually mattered for arrow.

**Comment by nassuphis** [comment]
it does, unfortunately

**Comment by nassuphis** [comment]
open_dataset(format="csv") does not work if files are .txt

**Comment by nassuphis** [comment]
line 97 in nlines-split.cpp

```
 sprintf(name_out, "%s_%d.txt", fn_out, ++nfile);
```
probably needs an extension agument

**Comment by privefl** [comment]
Have a look at `?arrow::dataset_factory()`; `format="csv"` is reading any text file assuming the delimiters are comma, this is not about the extension I think.
E.g. this works:
```r
dir.create(dir <- paste0(tempdir(), "TMP"))
tmp <- bigreadr::fwrite2(iris, tempfile(tmpdir = dir, fileext = ".txt"))
arrow::open_dataset(dir, format = "csv")
```

***

Anyway, if you really need this feature, I don't think it would be hard to implement, so I would appreciate if you could try doing it and providing a pull request.

**Comment by nassuphis** [comment]
aw. you are right. no need to fix then,

**Comment by nassuphis** [comment]
thanks for checking though.
i will try to find something useful to add.
